/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { SdgMappingListRelationFilter } from "../../sdgMapping/base/SdgMappingListRelationFilter";
import { SurveyResponseListRelationFilter } from "../../surveyResponse/base/SurveyResponseListRelationFilter";

@InputType()
class BusinessWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  industry?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  mission?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SdgMappingListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SdgMappingListRelationFilter)
  @IsOptional()
  @Field(() => SdgMappingListRelationFilter, {
    nullable: true,
  })
  sdgMappings?: SdgMappingListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SurveyResponseListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SurveyResponseListRelationFilter)
  @IsOptional()
  @Field(() => SurveyResponseListRelationFilter, {
    nullable: true,
  })
  surveyResponses?: SurveyResponseListRelationFilter;
}

export { BusinessWhereInput as BusinessWhereInput };
